languageCode = "en-us"
title = "My New Hugo Site"
baseURL = "http://example.org/"
theme = "../.."

[params]
    title = "Forty by HTML5 UP"
    major = "Hi, my name is Forty"
    subtitle = "A responsive site template designed by HTML5 UP"
    subtitleline2 = "and released under the Creative Commons."
    bannerCTA = "Get Started"

    [params.author]
      firstname = "Forty"
      lastname = "by HTML5 UP"

    [params.social]
      twitter = "twitter"
      facebook = "facebook"
      instagram = "instagram"
      github = "github"
      linkedin = "linkedin"
